- name: Stoping Mongodb
  service:
   name: mongod
   enabled: yes
   state: stopped

- name: Configuring mongod.conf
  template:
    src: mongoc.conf.j2
    dest: /etc/mongod.conf
    group: root
    owner: root
    mode: 0644
  notify:
   - starting mongodb 

- name: Creating File for intiation of replicaset with all configsvr member
  template:
    src: configsvr.js.j2
    dest: /tmp/configsvr.js
    group: mongod
    owner: mongod
    mode: 0755

- name: Stoping Mongodb
  service:
   name: mongod
   enabled: yes
   state: started

- name: Checking for ConfigServer Master Parametre
  shell: mongo --host {{ inventory_hostname }} --eval "rs.isMaster()" | grep "ismaster"
  register: result

- name: Initiating the replica set name with all configsvr member
  shell: mongo /tmp/configsvr.js --host {{ ansible_hostname }} --port {{ mongodb_port }}
  when: "{{inventory_hostname == groups['mongoc'][0]}}"
  ignore_errors: yes

 


